pipeline {
    agent any

    environment {
        PATH = "/usr/share/maven/bin:${PATH}"
    }

    stages {
        stage ('Show Environment Variables') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    ls -l /usr/share/maven/bin
                    /usr/share/maven/bin/mvn -version
                ''' 
            }
        }
    }

}