pipeline {
    agent any

    environment {
        PATH = "/usr/share/maven:${PATH}"
    }

    stages {
        stage ('Show Environment Variables') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    mvn -version
                ''' 
            }
        }
    }

}