pipeline {
    agent any

    stages {
        stage ('Show Environment Variables') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    mvn -version
                ''' 
            }
        }
    }

}